# Generated by Django 2.2.1 on 2019-07-10 09:14

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('main', '0012_auto_20190710_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('DependentManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
