# Generated by Django 2.2.1 on 2019-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='avgmark',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='avgmark',
            name='terminal_mark',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='avgmark',
            name='mark',
            field=models.FloatField(null=True),
        ),
    ]
