# Generated by Django 2.2.1 on 2019-07-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_auto_20190710_1214'),
        ('summary', '0003_classavgmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvgMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True)),
                ('terminal_mark', models.SmallIntegerField(null=True)),
                ('diff', models.FloatField(null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectAvgMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True)),
                ('terminal_mark', models.SmallIntegerField(null=True)),
                ('diff', models.FloatField(null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
