# Generated by Django 2.2.1 on 2019-07-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summary', '0005_auto_20190723_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='classavgmark',
            name='year',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectavgmark',
            name='year',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacheravgmark',
            name='year',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
