# Generated by Django 2.2.1 on 2019-07-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summary', '0006_auto_20190723_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classavgmark',
            name='terminal_mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectavgmark',
            name='terminal_mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teacheravgmark',
            name='terminal_mark',
            field=models.FloatField(null=True),
        ),
    ]
